sonar.organization=genesys-fatec
sonar.projectKey=genesys-fatec_API-4DSM-BACKEND
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/routes/**,src/middleware/**,src/utils/**,src/server.ts